export const TYPE_TASK = {
  GET_ALL_TASK: "GET_ALL_TASK",
  ADD_NEW_TASK: "ADD_NEW_TASK",
  DELETE_TASK: "DELETE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  GET_TASK_BY_ID: "GET_TASK_BY_ID",
};

export const TYPE_LOCALSTORAGE = {
  TASKS_KEY: "tasks",
};
